default_model = "llama32-1b"

[models."qwen2.5-coder-0.5b"]
model_type = "basic"
context_size = 4096
n_vocab = 151936
bos_token = 151643
eos_token = 151643
tokenizer = "/home/daniel/Qwen2.5-0.5B-v68/tokenizer.json"
ctx_bins = ["/home/daniel/Qwen2.5-0.5B-v68/qwen2.5-0.5b.bin"]
chat_template = "<|im_start|>system\n{system_prompt}<|im_end|>\n<|im_start|>user\n{user_input}<|im_end|>\n<|im_start|>assistant\n"
backend_type = "QnnGenAiTransformer"

[models."llama32-1b"]
model_type = "basic"
context_size = 1024
n_vocab = 128256
bos_token = 128000
eos_token = 128009
pad_token = 128004
tokenizer = "/home/daniel/llama-v68-model/tokenizer.json"
ctx_bins = ["/home/daniel/llama-v68-model/models/weight_sharing_model_1_of_1.serialized.bin"]
chat_template = "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n{system_prompt}<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{user_input}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
backend_type = "QnnHtp"
kv_dim = 64
pos_id_dim = 32
rope_theta = 500000.0
htp_poll = true
htp_ext = "/home/daniel/llama-v68-model/htp_backend_ext_config.json"
